### ISSUE TITLE
Example build run error

### ISSUE THREAD

**Issue by Shamik07** [invertase/flutter_desktop_webview_auth#12]
Getting the following error when I try to run the example app 

[  +37 ms] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: The command "setlocal [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[   +2 ms] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: C:\Windows\nuget.exe install Microsoft.Windows.ImplementationLibrary -Version 1.0.211019.2 -ExcludeVersion -OutputDirectory F:/ForkedForFlutterProduction/shamik/flutter_desktop_webview_auth/example/build/windows/packages [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: C:\Windows\nuget.exe install Microsoft.Web.WebView2 -Version 1.0.1108.44 -ExcludeVersion -OutputDirectory F:/ForkedForFlutterProduction/shamik/flutter_desktop_webview_auth/example/build/windows/packages [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :cmEnd [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :cmErrorLevel [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: exit /b %1 [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :cmDone [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :VCEnd" exited with code 1. [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: The command "setlocal [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: C:\Windows\nuget.exe install Microsoft.Windows.ImplementationLibrary -Version 1.0.211019.2 -ExcludeVersion -OutputDirectory F:/ForkedForFlutterProduction/shamik/flutter_desktop_webview_auth/example/build/windows/packages [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: C:\Windows\nuget.exe install Microsoft.Web.WebView2 -Version 1.0.1108.44 -ExcludeVersion -OutputDirectory F:/ForkedForFlutterProduction/shamik/flutter_desktop_webview_auth/example/build/windows/packages [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :cmEnd [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :cmErrorLevel [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: exit /b %1 [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :cmDone [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
[        ] C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :VCEnd" exited with code 1. [F:\ForkedForFlutterProduction\shamik\flutter_desktop_webview_auth\example\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]

[+5342 ms] Exception: Build process failed.
[   +7 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:590:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1165:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>

My flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.12.0-4.1.pre, on Microsoft Windows [Version 10.0.19042.1586], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

**Comment by Shamik07** [comment]
Getting this error when I make a new flutter project and just include the 0.0.6 package and run the app 

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: The command "setlocal [C:\Work\dump\dump\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: C:\Windows\nuget.exe install Microsoft.Windows.ImplementationLibrary -Version 1.0.211019.2 -ExcludeVersion -OutputDirectory C:/Work/dump/dump/build/win
dows/packages [C:\Work\dump\dump\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Work\dump\dump\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: C:\Windows\nuget.exe install Microsoft.Web.WebView2 -Version 1.0.1108.44 -ExcludeVersion -OutputDirectory C:/Work/dump/dump/build/windows/packages [C:\
Work\dump\dump\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Work\dump\dump\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :cmEnd [C:\Work\dump\dump\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\Work\dump\dump\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(147,5): error MSB3073: :cmErrorLevel [C:\Work\dump\dump\build\windows\plugins\desktop_webview_auth\DEPENDENCIES_DOWNLOAD.vcxproj]

**Comment by pr-Mais** [comment]
Try cleaning Nuget's cache as [mentioned here](https://stackoverflow.com/questions/54738695/package-is-not-found-in-the-following-primary-source/56997170#56997170).
Also, make sure you have the [additional requirements for windows development in Flutter](https://docs.flutter.dev/desktop#additional-windows-requirements).

**Comment by Shamik07** [comment]
Thanks! Clearing the Nuget cache fixed the issue. I already had Visual Studio 2022... Just need to clear the cache.

For anyone else facing the same issue, Update to Visual Studio 2022, Open it, "Tools -> Options -> Nuget -> General and click on the "Clear All Nuget Cache(s)" button.

Thanks again for the solution!
