### ISSUE TITLE
'Couldn't sign you in' popup on Google sign in 

### ISSUE THREAD

**Issue by Shamik07** [invertase/flutter_desktop_webview_auth#13]
I have the same issue open on the Flutter Fire desktop package... I thought this was a problem specific to the FlutterFire desktop package, but today I Ran the example app (flutter_desktop_webview_auth) (Windows 10), it runs perfectly, When I try the Google Sign In option the pop asking me for the email or phone number pops up but when I enter my email and try to sign in I get a
Couldn't sign you in... This browser or app may not be secure. Window

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.19042.1586], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.1)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!

![159987385-52af4e4f-ac0b-4e31-992e-5681b76eb170](https://user-images.githubusercontent.com/8936255/160847806-75b11b3d-3bab-4296-88c0-a23503aff700.jpg)

**Comment by Shamik07** [comment]
Version 100.0.1185.29 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/8936255/161702721-00f92460-8aae-416e-b639-2bb4092db5c3.png)

**Comment by pr-Mais** [comment]
The issue here is that Google is rejecting the WebView2, [see here](https://developers.google.com/identity/protocols/oauth2/policies#browsers). 
Related issue jnschulze/flutter-webview-windows#66
I'm not sure why it works on some devices. I'll update you soon if I could find a workaround.

**Comment by pr-Mais** [comment]
@Shamik07 could you please try running the example app on the current `main` branch? let me know if you're still facing the same issue.

**Comment by PavelPZ** [comment]
The same error for me (desktop_webview_auth: ^0.0.6 in pubspec.yaml) 

Whan I clone ```flutter_desktop_webview_auth``` repo and use dependency override for ```main``` branch, everything is OK:
```
dependency_overrides:
  desktop_webview_auth:
    path: d:/github/flutter_desktop_webview_auth
```

**Comment by pr-Mais** [comment]
Hey @PavelPZ, you could sign in with Google when you used the main branch?

**Comment by PavelPZ** [comment]
Yes, main branch is working for me.
Is it possible to update the pub.dev package?

**Comment by pr-Mais** [comment]
Amazing, sure! will push an update soon, thanks for confirming.

**Comment by Shamik07** [comment]
> @Shamik07 could you please try running the example app on the current `main` branch? let me know if you're still facing the same issue.

Yes!! It's working now! Thanks for the fix. Sorry for the late reply.
