### ISSUE TITLE
Get Refresh Token

### ISSUE THREAD

**Issue by f1dz** [invertase/flutter_desktop_webview_auth#27]
Thanks for your plugins.
Is it possible to get ```refresh_token```?
I already try to edit the ```AuthResult``` class and also pass ```prompt=consent``` into the query parameter, but ```reset_token``` never come up.

Thanks

**Comment by f1dz** [comment]
Fixed. 
I have made some changes, if someone is interested with the changes you can have a visit to my repo, or I will make a PR if you want to.

Cheers

**Comment by remcova** [comment]
@f1dz Can you make an PR?
