### ISSUE TITLE
Two different screens are shown, one doesn't work.

### ISSUE THREAD

**Issue by jungti1234** [invertase/flutter_desktop_webview_auth#49]
Hello. Thanks for this package.

Sometimes I can not signed in and the webview closed when I entered email and pressed enter or the next button.

Then I realized that I was seeing two different screens at random.

But when I read the logs, it was definitely the same URL.

<img width="1092" alt="스크린샷 2023-08-25 21 00 48" src="https://github.com/invertase/flutter_desktop_webview_auth/assets/17401597/9c8db2ef-fa65-42da-9f01-73e004de4f3b">

This is working.

<img width="1092" alt="스크린샷 2023-08-25 21 00 35" src="https://github.com/invertase/flutter_desktop_webview_auth/assets/17401597/130b94e0-6094-4ebe-aa7e-25ad50cef32b">

This is not working.

Any solution for this?

**Comment by remcova** [comment]
I have the same issue. I get to see the second screen that you've shown.

**Comment by remcova** [comment]
Update: See https://github.com/invertase/flutter_desktop_webview_auth/issues/50#issuecomment-1700989016

**Comment by remcova** [comment]
@jungti1234 I solved the issue. You can find it here https://github.com/invertase/flutter_desktop_webview_auth/issues/50#issuecomment-1702535564

**Comment by jungti1234** [comment]
@remcova It's working!! Thank you so much!
