### ISSUE TITLE
Result always null

### ISSUE THREAD

**Issue by remcova** [invertase/flutter_desktop_webview_auth#50]
Everytime I try to sign in via Google the result variable is null.
``` 
final result = await DesktopWebviewAuth.signIn(GoogleSignInArgs(
      clientId: GOOGLE_CLIENT_ID,
      redirectUri: REDIRECT_URI,
      scope: 'email',
    ));
```

The package worked fine before but now it's broken. I also tried to run the example but I experience the same issues there.
I've reinstalled all dependencies, updated the dependencies but nothing works. 

Any suggestions?

**Comment by remcova** [comment]
Update: I've created a new project and tested the package again, still not working. It seems broken at the moment.

**Comment by remcova** [comment]
Final update! You can download the fix from my forked repo https://github.com/remcova/flutter_desktop_webview_auth/tree/oauth_google_bug_fix

**Comment by remcova** [comment]
Issue closed. If this issue recurs, let me know.

**Comment by Tonku** [comment]
Thank you so much! raise a pr please

**Comment by jungti1234** [comment]
I appriciate you again for you solved. Do you mind if I ask one more thing?

In your example, I saw the value of scope contains "https://www.googleapis.com/auth/youtube".
- here: https://github.com/remcova/flutter_desktop_webview_auth/commit/02c4a0168f33e7f14675185019c8967084f7b517#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15

I tried testing this and got the error "Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.".
I had already set the redirect URL,
Presumably it happens at the point after sign in that when I get permission FIRST TIME for some API's scopes and then redirect.

Are you getting the same issue?

**Comment by remcova** [comment]
> I appriciate you again for you solved. Do you mind if I ask one more thing?
> 
> In your example, I saw the value of scope contains "https://www.googleapis.com/auth/youtube".
> 
> * here: [remcova@02c4a01#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15](https://github.com/remcova/flutter_desktop_webview_auth/commit/02c4a0168f33e7f14675185019c8967084f7b517#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15)
> 
> I tried testing this and got the error "Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.". I had already set the redirect URL, Presumably it happens at the point after sign in that when I get permission FIRST TIME for some API's scopes and then redirect.
> 
> Are you getting the same issue?

I only get this error when I use the "prompt" parameter and set it to "consent". It's not related to the YouTube scope. This is really unfortunate because I need this parameter to get the refresh_token to keep the user signed in.

**Comment by jungti1234** [comment]
> > I appriciate you again for you solved. Do you mind if I ask one more thing?
> > In your example, I saw the value of scope contains "https://www.googleapis.com/auth/youtube".
> > 
> > * here: [remcova@02c4a01#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15](https://github.com/remcova/flutter_desktop_webview_auth/commit/02c4a0168f33e7f14675185019c8967084f7b517#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15)
> > 
> > I tried testing this and got the error "Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.". I had already set the redirect URL, Presumably it happens at the point after sign in that when I get permission FIRST TIME for some API's scopes and then redirect.
> > Are you getting the same issue?
> 
> I only get this error when I use the "prompt" parameter and set it to "consent". It's not related to the YouTube scope. This is really unfortunate because I need this parameter to get the refresh_token to keep the user signed in.

Please try new scope that you never consent yet. I think you will have the same problem as me then.
I don't think it's perfectly same issue, but the error message is the same and it happens after the consent screen, so it could be the similer problem.

**Comment by remcova** [comment]
> > > I appriciate you again for you solved. Do you mind if I ask one more thing?
> > > In your example, I saw the value of scope contains "https://www.googleapis.com/auth/youtube".
> > > 
> > > * here: [remcova@02c4a01#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15](https://github.com/remcova/flutter_desktop_webview_auth/commit/02c4a0168f33e7f14675185019c8967084f7b517#diff-72fd825ad17ce7800a2078e06f0dff1e12836ee59760465e78d9a5d222cebd15)
> > > 
> > > I tried testing this and got the error "Unable to process request due to missing initial state. This may happen if browser sessionStorage is inaccessible or accidentally cleared.". I had already set the redirect URL, Presumably it happens at the point after sign in that when I get permission FIRST TIME for some API's scopes and then redirect.
> > > Are you getting the same issue?
> > 
> > 
> > I only get this error when I use the "prompt" parameter and set it to "consent". It's not related to the YouTube scope. This is really unfortunate because I need this parameter to get the refresh_token to keep the user signed in.
> 
> Please try new scope that you never consent yet. I think you will have the same problem as me then. I don't think it's perfectly same issue, but the error message is the same and it happens after the consent screen, so it could be the similer problem.

Yeah, I believe you. I'm afraid I won't be able to investigate this issue further in the coming days. I will be on holiday. It would be nice if one of the contributors could look into this issue.
